### ISSUE TITLE
missing array_modify spec

### ISSUE THREAD

**Issue by clausmichele** [eodcgmbh/openeo-processes#18]
@ValentinaHutter @GeraldIr 
In openeo-processes-dask, the `array_modify` process is implemented. However, the .json definition is missing here and therefore can't be really used. https://github.com/Open-EO/openeo-processes-dask/blob/8d9e3fb009676a39c3ce5009bc1c09909e5bbfb3/openeo_processes_dask/process_implementations/arrays.py#L93

There should be an automatic check to see if all the implemented processes have their corresponding spec in this repo.

**Comment by ValentinaHutter** [comment]
The `array_modify` specification is already available, so I am closing this.
